// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/token.proto

package tokenrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTokenRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Allowed              string   `protobuf:"bytes,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Whitelist            string   `protobuf:"bytes,4,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTokenRequest) Reset()         { *m = CreateTokenRequest{} }
func (m *CreateTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTokenRequest) ProtoMessage()    {}
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0498de655d1970f6, []int{0}
}

func (m *CreateTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTokenRequest.Unmarshal(m, b)
}
func (m *CreateTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTokenRequest.Marshal(b, m, deterministic)
}
func (m *CreateTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTokenRequest.Merge(m, src)
}
func (m *CreateTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTokenRequest.Size(m)
}
func (m *CreateTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTokenRequest proto.InternalMessageInfo

func (m *CreateTokenRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateTokenRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *CreateTokenRequest) GetAllowed() string {
	if m != nil {
		return m.Allowed
	}
	return ""
}

func (m *CreateTokenRequest) GetWhitelist() string {
	if m != nil {
		return m.Whitelist
	}
	return ""
}

type TokenResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AuthId               string   `protobuf:"bytes,3,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	Allowed              string   `protobuf:"bytes,4,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Whitelist            string   `protobuf:"bytes,5,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0498de655d1970f6, []int{1}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

func (m *TokenResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TokenResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TokenResponse) GetAuthId() string {
	if m != nil {
		return m.AuthId
	}
	return ""
}

func (m *TokenResponse) GetAllowed() string {
	if m != nil {
		return m.Allowed
	}
	return ""
}

func (m *TokenResponse) GetWhitelist() string {
	if m != nil {
		return m.Whitelist
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTokenRequest)(nil), "token.CreateTokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "token.TokenResponse")
}

func init() { proto.RegisterFile("proto/token.proto", fileDescriptor_0498de655d1970f6) }

var fileDescriptor_0498de655d1970f6 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0x34, 0x4d, 0xd4, 0xe3, 0x43, 0xe2, 0x84, 0xd4, 0x80, 0x18, 0xaa, 0x4e, 0x5d,
	0x9a, 0xa0, 0xb2, 0x33, 0xc0, 0xd4, 0x85, 0x21, 0x30, 0xb1, 0xa0, 0xd4, 0x39, 0x35, 0x16, 0x69,
	0x6d, 0xec, 0x0b, 0x55, 0x77, 0xfe, 0x70, 0x64, 0xa7, 0x40, 0xf9, 0x10, 0xdb, 0x7b, 0x77, 0xc3,
	0xfb, 0xdd, 0x3b, 0x38, 0xd1, 0x46, 0xb1, 0xca, 0x59, 0x3d, 0xd3, 0x3a, 0xf3, 0x1a, 0xfb, 0xde,
	0x8c, 0xb7, 0x80, 0xb7, 0x86, 0x4a, 0xa6, 0x07, 0x67, 0x0b, 0x7a, 0x69, 0xc9, 0x32, 0x0e, 0x21,
	0x69, 0x2d, 0x99, 0x27, 0x59, 0xa5, 0xc1, 0x28, 0x98, 0xf4, 0x8a, 0xd8, 0xd9, 0x79, 0x85, 0x08,
	0x11, 0x6f, 0x35, 0xa5, 0xe1, 0x28, 0x98, 0x0c, 0x0a, 0xaf, 0x31, 0x85, 0xa4, 0x6c, 0x1a, 0xb5,
	0xa1, 0x2a, 0xed, 0xf9, 0xf1, 0x87, 0xc5, 0x0b, 0x18, 0x6c, 0x6a, 0xc9, 0xd4, 0x48, 0xcb, 0x69,
	0xe4, 0x77, 0x5f, 0x83, 0xf1, 0x5b, 0x00, 0x47, 0xbb, 0x54, 0xab, 0xd5, 0xda, 0x12, 0x1e, 0x43,
	0xf8, 0x99, 0x18, 0xca, 0xbf, 0xd3, 0x86, 0x90, 0x94, 0x2d, 0xd7, 0x0e, 0xad, 0x4b, 0x8b, 0x9d,
	0x9d, 0x57, 0xfb, 0x18, 0xd1, 0x3f, 0x18, 0xfd, 0x1f, 0x18, 0xb3, 0x3b, 0x38, 0xf4, 0x14, 0xf7,
	0x64, 0x5e, 0xa5, 0x20, 0xbc, 0x86, 0x83, 0xbd, 0x46, 0xf0, 0x2c, 0xeb, 0x5a, 0xfb, 0xdd, 0xd2,
	0xf9, 0xe9, 0x6e, 0xf5, 0xed, 0x88, 0x9b, 0xd9, 0xe3, 0xe5, 0x52, 0x72, 0xdd, 0x2e, 0x32, 0xa1,
	0x56, 0xb9, 0x2d, 0x59, 0xae, 0x5c, 0xf7, 0x4b, 0x35, 0x55, 0x42, 0xcb, 0x69, 0xa9, 0x65, 0xee,
	0x84, 0xd1, 0xa2, 0xfb, 0x87, 0xd1, 0x62, 0x11, 0xfb, 0x9f, 0x5c, 0xbd, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0xd4, 0x00, 0xdf, 0xa8, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenServiceClient is the client API for TokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenServiceClient interface {
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
}

type tokenServiceClient struct {
	cc *grpc.ClientConn
}

func NewTokenServiceClient(cc *grpc.ClientConn) TokenServiceClient {
	return &tokenServiceClient{cc}
}

func (c *tokenServiceClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/token.TokenService/CreateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServiceServer is the server API for TokenService service.
type TokenServiceServer interface {
	CreateToken(context.Context, *CreateTokenRequest) (*TokenResponse, error)
}

// UnimplementedTokenServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenServiceServer struct {
}

func (*UnimplementedTokenServiceServer) CreateToken(ctx context.Context, req *CreateTokenRequest) (*TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToken not implemented")
}

func RegisterTokenServiceServer(s *grpc.Server, srv TokenServiceServer) {
	s.RegisterService(&_TokenService_serviceDesc, srv)
}

func _TokenService_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServiceServer).CreateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/token.TokenService/CreateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServiceServer).CreateToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "token.TokenService",
	HandlerType: (*TokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken",
			Handler:    _TokenService_CreateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/token.proto",
}
