// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocpirpc/businessdetail.proto

package ocpirpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBusinessDetailRequest struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Website              string              `protobuf:"bytes,2,opt,name=website,proto3" json:"website,omitempty"`
	Logo                 *CreateImageRequest `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateBusinessDetailRequest) Reset()         { *m = CreateBusinessDetailRequest{} }
func (m *CreateBusinessDetailRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBusinessDetailRequest) ProtoMessage()    {}
func (*CreateBusinessDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c6e5ea221dc866f, []int{0}
}

func (m *CreateBusinessDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBusinessDetailRequest.Unmarshal(m, b)
}
func (m *CreateBusinessDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBusinessDetailRequest.Marshal(b, m, deterministic)
}
func (m *CreateBusinessDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBusinessDetailRequest.Merge(m, src)
}
func (m *CreateBusinessDetailRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBusinessDetailRequest.Size(m)
}
func (m *CreateBusinessDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBusinessDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBusinessDetailRequest proto.InternalMessageInfo

func (m *CreateBusinessDetailRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateBusinessDetailRequest) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *CreateBusinessDetailRequest) GetLogo() *CreateImageRequest {
	if m != nil {
		return m.Logo
	}
	return nil
}

type BusinessDetailResponse struct {
	Id                   int64          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Website              string         `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	Logo                 *ImageResponse `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BusinessDetailResponse) Reset()         { *m = BusinessDetailResponse{} }
func (m *BusinessDetailResponse) String() string { return proto.CompactTextString(m) }
func (*BusinessDetailResponse) ProtoMessage()    {}
func (*BusinessDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c6e5ea221dc866f, []int{1}
}

func (m *BusinessDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessDetailResponse.Unmarshal(m, b)
}
func (m *BusinessDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessDetailResponse.Marshal(b, m, deterministic)
}
func (m *BusinessDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessDetailResponse.Merge(m, src)
}
func (m *BusinessDetailResponse) XXX_Size() int {
	return xxx_messageInfo_BusinessDetailResponse.Size(m)
}
func (m *BusinessDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessDetailResponse proto.InternalMessageInfo

func (m *BusinessDetailResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BusinessDetailResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BusinessDetailResponse) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *BusinessDetailResponse) GetLogo() *ImageResponse {
	if m != nil {
		return m.Logo
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateBusinessDetailRequest)(nil), "businessdetail.CreateBusinessDetailRequest")
	proto.RegisterType((*BusinessDetailResponse)(nil), "businessdetail.BusinessDetailResponse")
}

func init() { proto.RegisterFile("ocpirpc/businessdetail.proto", fileDescriptor_6c6e5ea221dc866f) }

var fileDescriptor_6c6e5ea221dc866f = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0xc9, 0x07, 0x8a, 0x2b, 0x5c, 0xb1, 0x8a, 0xc4, 0x8f, 0xe2, 0xb8, 0xc6, 0x58, 0x24,
	0x01, 0xfd, 0x07, 0xa7, 0x8d, 0x6d, 0x4a, 0xbb, 0x4d, 0x32, 0xc4, 0x81, 0xdb, 0xcc, 0x9a, 0x99,
	0x20, 0x58, 0xf9, 0xd3, 0xe5, 0x76, 0xf7, 0x84, 0x13, 0xbb, 0x99, 0xe1, 0x61, 0xde, 0x87, 0x57,
	0xdd, 0x51, 0xef, 0x70, 0x76, 0x7d, 0xd3, 0x2d, 0x8c, 0x13, 0x30, 0x0f, 0x20, 0x06, 0x77, 0xb5,
	0x9b, 0x49, 0x48, 0xaf, 0x8e, 0xaf, 0x37, 0x17, 0x07, 0x1a, 0xad, 0x19, 0x21, 0x40, 0x9b, 0x2f,
	0x75, 0xfb, 0x3c, 0x83, 0x11, 0xd8, 0x46, 0xf8, 0xc5, 0xc3, 0x2d, 0x7c, 0x2c, 0xc0, 0xa2, 0xb5,
	0xca, 0x27, 0x63, 0xa1, 0x48, 0xd6, 0x49, 0x79, 0xd6, 0xfa, 0x59, 0x17, 0xea, 0xf4, 0x13, 0x3a,
	0x46, 0x81, 0x22, 0xf5, 0xe7, 0xc3, 0xaa, 0x2b, 0x95, 0xef, 0x68, 0xa4, 0x22, 0x5b, 0x27, 0xe5,
	0xf9, 0xe3, 0x75, 0x1d, 0x82, 0xc2, 0xff, 0xd7, 0xfd, 0x1c, 0xdf, 0xb6, 0x1e, 0xdb, 0x7c, 0x27,
	0xea, 0xea, 0x6f, 0x2c, 0x3b, 0x9a, 0x18, 0xf4, 0x4a, 0xa5, 0x38, 0xf8, 0xd4, 0xac, 0x4d, 0x71,
	0xf8, 0xf5, 0x48, 0xff, 0xf7, 0xc8, 0x8e, 0x3d, 0xca, 0xe8, 0x91, 0x7b, 0x8f, 0xcb, 0xe8, 0x11,
	0x0d, 0x42, 0x42, 0x50, 0xd8, 0x3e, 0xbc, 0xdd, 0x8f, 0x28, 0xef, 0x4b, 0x57, 0xf7, 0x64, 0x1b,
	0x36, 0x82, 0x96, 0x84, 0x9a, 0x91, 0xaa, 0x7d, 0x59, 0x95, 0x71, 0xd8, 0xc4, 0xd6, 0xba, 0x13,
	0x5f, 0xd8, 0xd3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x9e, 0xf9, 0x25, 0x75, 0x01, 0x00,
	0x00,
}
