// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/businessdetail.proto

package ocpirpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Website              string   `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	Logo                 *Image   `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessDetail) Reset()         { *m = BusinessDetail{} }
func (m *BusinessDetail) String() string { return proto.CompactTextString(m) }
func (*BusinessDetail) ProtoMessage()    {}
func (*BusinessDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f3efe37e6dff331, []int{0}
}

func (m *BusinessDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessDetail.Unmarshal(m, b)
}
func (m *BusinessDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessDetail.Marshal(b, m, deterministic)
}
func (m *BusinessDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessDetail.Merge(m, src)
}
func (m *BusinessDetail) XXX_Size() int {
	return xxx_messageInfo_BusinessDetail.Size(m)
}
func (m *BusinessDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessDetail.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessDetail proto.InternalMessageInfo

func (m *BusinessDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BusinessDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BusinessDetail) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *BusinessDetail) GetLogo() *Image {
	if m != nil {
		return m.Logo
	}
	return nil
}

func init() {
	proto.RegisterType((*BusinessDetail)(nil), "businessdetail.BusinessDetail")
}

func init() { proto.RegisterFile("proto/businessdetail.proto", fileDescriptor_5f3efe37e6dff331) }

var fileDescriptor_5f3efe37e6dff331 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8e, 0x31, 0xab, 0x83, 0x30,
	0x10, 0xc7, 0x89, 0xca, 0x7b, 0xbc, 0xbc, 0x22, 0x34, 0x53, 0x70, 0x0a, 0x5d, 0x6a, 0x07, 0x15,
	0xda, 0x6f, 0x20, 0x5d, 0xba, 0x3a, 0x76, 0x4b, 0x34, 0xa4, 0x07, 0xc6, 0x0b, 0x26, 0xd2, 0xaf,
	0x5f, 0x8c, 0xed, 0xd0, 0xe5, 0xf8, 0xdf, 0xef, 0x7e, 0x70, 0x7f, 0x5a, 0xb8, 0x19, 0x03, 0x36,
	0x6a, 0xf1, 0x30, 0x69, 0xef, 0x07, 0x1d, 0x24, 0x8c, 0x75, 0x84, 0x2c, 0xff, 0xa6, 0xc5, 0x7e,
	0x73, 0xc1, 0x4a, 0xa3, 0x37, 0xe5, 0xe0, 0x68, 0xde, 0xbe, 0xa5, 0x6b, 0x94, 0x58, 0x4e, 0x13,
	0x18, 0x38, 0x11, 0xa4, 0x4c, 0xbb, 0x04, 0x06, 0xc6, 0x68, 0x36, 0x49, 0xab, 0x79, 0x22, 0x48,
	0xf9, 0xd7, 0xc5, 0xcc, 0x38, 0xfd, 0x7d, 0x6a, 0xe5, 0x21, 0x68, 0x9e, 0x46, 0xfc, 0x59, 0x99,
	0xa0, 0xd9, 0x88, 0x06, 0x79, 0x26, 0x48, 0xf9, 0x7f, 0xde, 0xd5, 0xdb, 0xaf, 0xdb, 0x3a, 0xbb,
	0x78, 0x69, 0x4f, 0xf7, 0xa3, 0x81, 0xf0, 0x58, 0x54, 0xdd, 0xa3, 0x6d, 0xbc, 0x0c, 0x60, 0xd7,
	0x52, 0x06, 0x2b, 0xec, 0x1d, 0x54, 0xd2, 0x41, 0xb3, 0x86, 0xd9, 0xf5, 0xea, 0x27, 0x76, 0xbc,
	0xbc, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xed, 0x73, 0x43, 0xe4, 0x00, 0x00, 0x00,
}
