// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocpirpc/command.proto

package ocpirpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReserveNowRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,2,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	LocationUid          string   `protobuf:"bytes,3,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,4,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveNowRequest) Reset()         { *m = ReserveNowRequest{} }
func (m *ReserveNowRequest) String() string { return proto.CompactTextString(m) }
func (*ReserveNowRequest) ProtoMessage()    {}
func (*ReserveNowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{0}
}

func (m *ReserveNowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveNowRequest.Unmarshal(m, b)
}
func (m *ReserveNowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveNowRequest.Marshal(b, m, deterministic)
}
func (m *ReserveNowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveNowRequest.Merge(m, src)
}
func (m *ReserveNowRequest) XXX_Size() int {
	return xxx_messageInfo_ReserveNowRequest.Size(m)
}
func (m *ReserveNowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveNowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveNowRequest proto.InternalMessageInfo

func (m *ReserveNowRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReserveNowRequest) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *ReserveNowRequest) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *ReserveNowRequest) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

type ReserveNowResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ReservationId        int64    `protobuf:"varint,3,opt,name=reservationId,proto3" json:"reservationId,omitempty"`
	ExpiryDate           string   `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	LocationUid          string   `protobuf:"bytes,5,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,6,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReserveNowResponse) Reset()         { *m = ReserveNowResponse{} }
func (m *ReserveNowResponse) String() string { return proto.CompactTextString(m) }
func (*ReserveNowResponse) ProtoMessage()    {}
func (*ReserveNowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{1}
}

func (m *ReserveNowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReserveNowResponse.Unmarshal(m, b)
}
func (m *ReserveNowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReserveNowResponse.Marshal(b, m, deterministic)
}
func (m *ReserveNowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReserveNowResponse.Merge(m, src)
}
func (m *ReserveNowResponse) XXX_Size() int {
	return xxx_messageInfo_ReserveNowResponse.Size(m)
}
func (m *ReserveNowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReserveNowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReserveNowResponse proto.InternalMessageInfo

func (m *ReserveNowResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReserveNowResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReserveNowResponse) GetReservationId() int64 {
	if m != nil {
		return m.ReservationId
	}
	return 0
}

func (m *ReserveNowResponse) GetExpiryDate() string {
	if m != nil {
		return m.ExpiryDate
	}
	return ""
}

func (m *ReserveNowResponse) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *ReserveNowResponse) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

type StartSessionRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LocationUid          string   `protobuf:"bytes,2,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,3,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSessionRequest) Reset()         { *m = StartSessionRequest{} }
func (m *StartSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StartSessionRequest) ProtoMessage()    {}
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{2}
}

func (m *StartSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionRequest.Unmarshal(m, b)
}
func (m *StartSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionRequest.Marshal(b, m, deterministic)
}
func (m *StartSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionRequest.Merge(m, src)
}
func (m *StartSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StartSessionRequest.Size(m)
}
func (m *StartSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionRequest proto.InternalMessageInfo

func (m *StartSessionRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StartSessionRequest) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *StartSessionRequest) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

type StartSessionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	AuthorizationId      string   `protobuf:"bytes,3,opt,name=authorizationId,proto3" json:"authorizationId,omitempty"`
	VerificationKey      string   `protobuf:"bytes,4,opt,name=verificationKey,proto3" json:"verificationKey,omitempty"`
	LocationUid          string   `protobuf:"bytes,5,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,6,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSessionResponse) Reset()         { *m = StartSessionResponse{} }
func (m *StartSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StartSessionResponse) ProtoMessage()    {}
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{3}
}

func (m *StartSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionResponse.Unmarshal(m, b)
}
func (m *StartSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionResponse.Marshal(b, m, deterministic)
}
func (m *StartSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionResponse.Merge(m, src)
}
func (m *StartSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StartSessionResponse.Size(m)
}
func (m *StartSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionResponse proto.InternalMessageInfo

func (m *StartSessionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StartSessionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StartSessionResponse) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

func (m *StartSessionResponse) GetVerificationKey() string {
	if m != nil {
		return m.VerificationKey
	}
	return ""
}

func (m *StartSessionResponse) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *StartSessionResponse) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

type StopSessionRequest struct {
	SessionUid           string   `protobuf:"bytes,1,opt,name=session_uid,json=sessionUid,proto3" json:"session_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSessionRequest) Reset()         { *m = StopSessionRequest{} }
func (m *StopSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StopSessionRequest) ProtoMessage()    {}
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{4}
}

func (m *StopSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSessionRequest.Unmarshal(m, b)
}
func (m *StopSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSessionRequest.Marshal(b, m, deterministic)
}
func (m *StopSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSessionRequest.Merge(m, src)
}
func (m *StopSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StopSessionRequest.Size(m)
}
func (m *StopSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopSessionRequest proto.InternalMessageInfo

func (m *StopSessionRequest) GetSessionUid() string {
	if m != nil {
		return m.SessionUid
	}
	return ""
}

type StopSessionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	SessionUid           string   `protobuf:"bytes,3,opt,name=session_uid,json=sessionUid,proto3" json:"session_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSessionResponse) Reset()         { *m = StopSessionResponse{} }
func (m *StopSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StopSessionResponse) ProtoMessage()    {}
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{5}
}

func (m *StopSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSessionResponse.Unmarshal(m, b)
}
func (m *StopSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSessionResponse.Marshal(b, m, deterministic)
}
func (m *StopSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSessionResponse.Merge(m, src)
}
func (m *StopSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StopSessionResponse.Size(m)
}
func (m *StopSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopSessionResponse proto.InternalMessageInfo

func (m *StopSessionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StopSessionResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StopSessionResponse) GetSessionUid() string {
	if m != nil {
		return m.SessionUid
	}
	return ""
}

type UnlockConnectorRequest struct {
	LocationUid          string   `protobuf:"bytes,1,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,2,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	ConnectorUid         string   `protobuf:"bytes,3,opt,name=connector_uid,json=connectorUid,proto3" json:"connector_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockConnectorRequest) Reset()         { *m = UnlockConnectorRequest{} }
func (m *UnlockConnectorRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockConnectorRequest) ProtoMessage()    {}
func (*UnlockConnectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{6}
}

func (m *UnlockConnectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockConnectorRequest.Unmarshal(m, b)
}
func (m *UnlockConnectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockConnectorRequest.Marshal(b, m, deterministic)
}
func (m *UnlockConnectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockConnectorRequest.Merge(m, src)
}
func (m *UnlockConnectorRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockConnectorRequest.Size(m)
}
func (m *UnlockConnectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockConnectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockConnectorRequest proto.InternalMessageInfo

func (m *UnlockConnectorRequest) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *UnlockConnectorRequest) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

func (m *UnlockConnectorRequest) GetConnectorUid() string {
	if m != nil {
		return m.ConnectorUid
	}
	return ""
}

type UnlockConnectorResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LocationUid          string   `protobuf:"bytes,3,opt,name=location_uid,json=locationUid,proto3" json:"location_uid,omitempty"`
	EvseUid              string   `protobuf:"bytes,4,opt,name=evse_uid,json=evseUid,proto3" json:"evse_uid,omitempty"`
	ConnectorUid         string   `protobuf:"bytes,5,opt,name=connector_uid,json=connectorUid,proto3" json:"connector_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockConnectorResponse) Reset()         { *m = UnlockConnectorResponse{} }
func (m *UnlockConnectorResponse) String() string { return proto.CompactTextString(m) }
func (*UnlockConnectorResponse) ProtoMessage()    {}
func (*UnlockConnectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c9ab853259f9e2c, []int{7}
}

func (m *UnlockConnectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockConnectorResponse.Unmarshal(m, b)
}
func (m *UnlockConnectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockConnectorResponse.Marshal(b, m, deterministic)
}
func (m *UnlockConnectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockConnectorResponse.Merge(m, src)
}
func (m *UnlockConnectorResponse) XXX_Size() int {
	return xxx_messageInfo_UnlockConnectorResponse.Size(m)
}
func (m *UnlockConnectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockConnectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockConnectorResponse proto.InternalMessageInfo

func (m *UnlockConnectorResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UnlockConnectorResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UnlockConnectorResponse) GetLocationUid() string {
	if m != nil {
		return m.LocationUid
	}
	return ""
}

func (m *UnlockConnectorResponse) GetEvseUid() string {
	if m != nil {
		return m.EvseUid
	}
	return ""
}

func (m *UnlockConnectorResponse) GetConnectorUid() string {
	if m != nil {
		return m.ConnectorUid
	}
	return ""
}

func init() {
	proto.RegisterType((*ReserveNowRequest)(nil), "command.ReserveNowRequest")
	proto.RegisterType((*ReserveNowResponse)(nil), "command.ReserveNowResponse")
	proto.RegisterType((*StartSessionRequest)(nil), "command.StartSessionRequest")
	proto.RegisterType((*StartSessionResponse)(nil), "command.StartSessionResponse")
	proto.RegisterType((*StopSessionRequest)(nil), "command.StopSessionRequest")
	proto.RegisterType((*StopSessionResponse)(nil), "command.StopSessionResponse")
	proto.RegisterType((*UnlockConnectorRequest)(nil), "command.UnlockConnectorRequest")
	proto.RegisterType((*UnlockConnectorResponse)(nil), "command.UnlockConnectorResponse")
}

func init() { proto.RegisterFile("ocpirpc/command.proto", fileDescriptor_6c9ab853259f9e2c) }

var fileDescriptor_6c9ab853259f9e2c = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x96, 0x93, 0xad, 0x63, 0xa7, 0xdd, 0x26, 0x0c, 0x6c, 0x25, 0x1b, 0x6a, 0xd9, 0x40, 0xea,
	0x0d, 0xab, 0x04, 0xe2, 0x05, 0x18, 0x48, 0x4c, 0x93, 0xb8, 0x48, 0xe9, 0x0d, 0x17, 0x54, 0x59,
	0x72, 0xd8, 0x2c, 0xda, 0x9c, 0x60, 0x3b, 0x85, 0xc1, 0x23, 0xf0, 0x1a, 0xbc, 0x08, 0x12, 0x0f,
	0xc0, 0x23, 0xa1, 0x24, 0x6e, 0x49, 0x9c, 0xae, 0x53, 0xb5, 0x4b, 0x7f, 0xe7, 0xe7, 0x3b, 0xdf,
	0x67, 0xfb, 0xc0, 0x03, 0x0a, 0x13, 0x21, 0x93, 0xb0, 0x1f, 0xd2, 0x64, 0x12, 0xc4, 0xd1, 0x71,
	0x22, 0x49, 0x13, 0xdf, 0x30, 0xc7, 0xc3, 0x9f, 0x0c, 0xee, 0xfa, 0xa8, 0x50, 0x4e, 0xf1, 0x1d,
	0x7d, 0xf5, 0xf1, 0x4b, 0x8a, 0x4a, 0xf3, 0x3d, 0xd8, 0x48, 0x15, 0xca, 0x91, 0x88, 0xda, 0xac,
	0xcb, 0x7a, 0xae, 0xdf, 0xc8, 0x8e, 0xa7, 0x11, 0xef, 0x40, 0x13, 0xbf, 0x25, 0x42, 0x5e, 0x8d,
	0xa2, 0x40, 0x63, 0xdb, 0xe9, 0xb2, 0xde, 0xa6, 0x0f, 0x05, 0xf4, 0x3a, 0xd0, 0xc8, 0x1f, 0x43,
	0x6b, 0x4c, 0x61, 0xa0, 0x05, 0xc5, 0xa3, 0x54, 0x44, 0x6d, 0x37, 0xcf, 0x68, 0xce, 0xb0, 0xa1,
	0x88, 0xf8, 0x43, 0xb8, 0x83, 0x53, 0x85, 0x79, 0x78, 0x2d, 0x0f, 0x6f, 0x64, 0xe7, 0xa1, 0x88,
	0x0e, 0x7f, 0x33, 0xe0, 0xe5, 0x69, 0x54, 0x42, 0xb1, 0x42, 0xbe, 0x0d, 0xce, 0x7c, 0x12, 0x47,
	0x44, 0x7c, 0x17, 0x1a, 0x4a, 0x07, 0x3a, 0x55, 0x66, 0x00, 0x73, 0xe2, 0x4f, 0x60, 0x4b, 0xe6,
	0xd5, 0x39, 0xd7, 0x69, 0xc1, 0xee, 0xfa, 0x55, 0xd0, 0xd6, 0xb0, 0x76, 0xa3, 0x86, 0xf5, 0xe5,
	0x1a, 0x1a, 0x55, 0x0d, 0x63, 0xb8, 0x37, 0xd0, 0x81, 0xd4, 0x03, 0x54, 0x4a, 0x50, 0x7c, 0xa3,
	0xa5, 0x36, 0x9b, 0xb3, 0x9c, 0xcd, 0xad, 0xb2, 0xfd, 0x65, 0x70, 0xbf, 0x4a, 0xb7, 0xa2, 0x67,
	0x3d, 0xd8, 0x09, 0x52, 0x7d, 0x49, 0x52, 0x7c, 0x2f, 0xbb, 0xb6, 0xe9, 0xdb, 0x70, 0x96, 0x39,
	0x45, 0x29, 0x3e, 0x89, 0x62, 0xb0, 0x33, 0xbc, 0x32, 0xde, 0xd9, 0xf0, 0x2d, 0x0d, 0x7c, 0x09,
	0x7c, 0xa0, 0x29, 0xb1, 0xfc, 0xeb, 0x40, 0x53, 0x15, 0x48, 0x5e, 0xc3, 0x8a, 0x5b, 0x33, 0x50,
	0x56, 0xf6, 0x31, 0xf3, 0xbd, 0x54, 0xb6, 0xa2, 0x0f, 0x56, 0x7f, 0xb7, 0xd6, 0xff, 0x07, 0xec,
	0x0e, 0xe3, 0x31, 0x85, 0x9f, 0x4f, 0x28, 0x8e, 0x31, 0xd4, 0x24, 0x67, 0xa3, 0xd9, 0x72, 0xd9,
	0x72, 0xb9, 0x4e, 0x45, 0x2e, 0x3f, 0x82, 0xad, 0x70, 0xd6, 0xb1, 0x44, 0xdd, 0x9a, 0x83, 0x19,
	0xf9, 0x2f, 0x06, 0x7b, 0x35, 0xf6, 0x15, 0x15, 0xde, 0xea, 0x6b, 0xd6, 0xc7, 0x5c, 0xaf, 0x8f,
	0xf9, 0xfc, 0x8f, 0x03, 0xdb, 0x27, 0xc5, 0x66, 0x19, 0xa0, 0x9c, 0x8a, 0x10, 0xf9, 0x1b, 0x80,
	0xff, 0x3f, 0x9a, 0x7b, 0xc7, 0xb3, 0x3d, 0x54, 0x5b, 0x3a, 0xde, 0xfe, 0xc2, 0x98, 0x11, 0x79,
	0x06, 0xad, 0xf2, 0x33, 0xe7, 0x07, 0xf3, 0xe4, 0x05, 0x9f, 0xcd, 0x7b, 0x74, 0x4d, 0xd4, 0x34,
	0x7b, 0x0b, 0xcd, 0xd2, 0x53, 0xe1, 0xfb, 0xa5, 0x6c, 0xfb, 0xdd, 0x79, 0x07, 0x8b, 0x83, 0xa6,
	0xd3, 0x7b, 0xd8, 0xb1, 0xae, 0x85, 0x77, 0xe6, 0x05, 0x8b, 0x9f, 0x8b, 0xd7, 0xbd, 0x3e, 0xa1,
	0xe8, 0xfa, 0xea, 0xe9, 0x87, 0xa3, 0x0b, 0xa1, 0x2f, 0xd3, 0xf3, 0x2c, 0xb3, 0xaf, 0x02, 0x2d,
	0x26, 0xa4, 0xa9, 0x7f, 0x41, 0xcf, 0xb2, 0x6d, 0xde, 0x37, 0x2b, 0xfd, 0xbc, 0x91, 0xef, 0xf2,
	0x17, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xb3, 0xe2, 0x68, 0xe4, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandServiceClient interface {
	ReserveNow(ctx context.Context, in *ReserveNowRequest, opts ...grpc.CallOption) (*ReserveNowResponse, error)
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
	UnlockConnector(ctx context.Context, in *UnlockConnectorRequest, opts ...grpc.CallOption) (*UnlockConnectorResponse, error)
}

type commandServiceClient struct {
	cc *grpc.ClientConn
}

func NewCommandServiceClient(cc *grpc.ClientConn) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) ReserveNow(ctx context.Context, in *ReserveNowRequest, opts ...grpc.CallOption) (*ReserveNowResponse, error) {
	out := new(ReserveNowResponse)
	err := c.cc.Invoke(ctx, "/command.CommandService/ReserveNow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, "/command.CommandService/StartSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, "/command.CommandService/StopSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) UnlockConnector(ctx context.Context, in *UnlockConnectorRequest, opts ...grpc.CallOption) (*UnlockConnectorResponse, error) {
	out := new(UnlockConnectorResponse)
	err := c.cc.Invoke(ctx, "/command.CommandService/UnlockConnector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
type CommandServiceServer interface {
	ReserveNow(context.Context, *ReserveNowRequest) (*ReserveNowResponse, error)
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
	UnlockConnector(context.Context, *UnlockConnectorRequest) (*UnlockConnectorResponse, error)
}

// UnimplementedCommandServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (*UnimplementedCommandServiceServer) ReserveNow(ctx context.Context, req *ReserveNowRequest) (*ReserveNowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveNow not implemented")
}
func (*UnimplementedCommandServiceServer) StartSession(ctx context.Context, req *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (*UnimplementedCommandServiceServer) StopSession(ctx context.Context, req *StopSessionRequest) (*StopSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSession not implemented")
}
func (*UnimplementedCommandServiceServer) UnlockConnector(ctx context.Context, req *UnlockConnectorRequest) (*UnlockConnectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockConnector not implemented")
}

func RegisterCommandServiceServer(s *grpc.Server, srv CommandServiceServer) {
	s.RegisterService(&_CommandService_serviceDesc, srv)
}

func _CommandService_ReserveNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ReserveNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/command.CommandService/ReserveNow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ReserveNow(ctx, req.(*ReserveNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/command.CommandService/StartSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/command.CommandService/StopSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_UnlockConnector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockConnectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).UnlockConnector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/command.CommandService/UnlockConnector",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).UnlockConnector(ctx, req.(*UnlockConnectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "command.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveNow",
			Handler:    _CommandService_ReserveNow_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _CommandService_StartSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _CommandService_StopSession_Handler,
		},
		{
			MethodName: "UnlockConnector",
			Handler:    _CommandService_UnlockConnector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocpirpc/command.proto",
}
