// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/image.proto

package ocpirpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Image struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Thumbnail            string   `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Category             string   `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Width                int32    `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_042638d41ebcabe6, []int{0}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetThumbnail() string {
	if m != nil {
		return m.Thumbnail
	}
	return ""
}

func (m *Image) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Image) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*Image)(nil), "image.Image")
}

func init() { proto.RegisterFile("proto/image.proto", fileDescriptor_042638d41ebcabe6) }

var fileDescriptor_042638d41ebcabe6 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x3d, 0x4e, 0xc4, 0x30,
	0x10, 0x46, 0xe5, 0x64, 0x1d, 0xd8, 0x29, 0x10, 0x8c, 0x10, 0xb2, 0x10, 0x45, 0x44, 0x43, 0x28,
	0x76, 0x53, 0x70, 0x03, 0x3a, 0xda, 0x94, 0x74, 0xce, 0x8f, 0xec, 0x91, 0xd6, 0xd8, 0x32, 0x13,
	0xa1, 0x1c, 0x88, 0x7b, 0x22, 0x0f, 0x88, 0xed, 0xde, 0x7b, 0x5f, 0xf5, 0xc1, 0x4d, 0xca, 0x91,
	0x63, 0x4f, 0xc1, 0xba, 0xe5, 0x28, 0x8c, 0x5a, 0xe4, 0xf1, 0x5b, 0x81, 0x7e, 0x2b, 0x84, 0x57,
	0x50, 0xd1, 0x6c, 0x54, 0xab, 0xba, 0x7a, 0xa8, 0x68, 0xc6, 0x6b, 0xa8, 0xd7, 0x7c, 0x32, 0x55,
	0xab, 0xba, 0xfd, 0x50, 0x10, 0x1f, 0x60, 0xcf, 0x7e, 0x0d, 0xe3, 0x87, 0xa5, 0x93, 0xa9, 0xa5,
	0x9f, 0x03, 0xde, 0xc3, 0xe5, 0x64, 0x79, 0x71, 0x31, 0x6f, 0x66, 0x27, 0xe3, 0xbf, 0x23, 0xc2,
	0x8e, 0xb7, 0xb4, 0x18, 0x2d, 0x5d, 0x18, 0x6f, 0x41, 0x7f, 0xd1, 0xcc, 0xde, 0x34, 0xad, 0xea,
	0xf4, 0xf0, 0x2b, 0x78, 0x07, 0x8d, 0x5f, 0xc8, 0x79, 0x36, 0x17, 0x92, 0xff, 0xec, 0xf5, 0xf9,
	0xfd, 0xc9, 0x11, 0xfb, 0x75, 0x3c, 0x4e, 0x31, 0xf4, 0x9f, 0x96, 0x29, 0x94, 0x47, 0x2e, 0x1e,
	0xe2, 0x94, 0xe8, 0x60, 0x13, 0xf5, 0x05, 0x72, 0x9a, 0xc6, 0x46, 0x0e, 0xbe, 0xfc, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x38, 0x0b, 0x47, 0xde, 0xf5, 0x00, 0x00, 0x00,
}
