// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocpirpc/session.proto

package ocpirpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionCreatedRequest struct {
	SessionUid           string   `protobuf:"bytes,1,opt,name=session_uid,json=sessionUid,proto3" json:"session_uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionCreatedRequest) Reset()         { *m = SessionCreatedRequest{} }
func (m *SessionCreatedRequest) String() string { return proto.CompactTextString(m) }
func (*SessionCreatedRequest) ProtoMessage()    {}
func (*SessionCreatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c26b6320f4bed3, []int{0}
}

func (m *SessionCreatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCreatedRequest.Unmarshal(m, b)
}
func (m *SessionCreatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCreatedRequest.Marshal(b, m, deterministic)
}
func (m *SessionCreatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCreatedRequest.Merge(m, src)
}
func (m *SessionCreatedRequest) XXX_Size() int {
	return xxx_messageInfo_SessionCreatedRequest.Size(m)
}
func (m *SessionCreatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCreatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCreatedRequest proto.InternalMessageInfo

func (m *SessionCreatedRequest) GetSessionUid() string {
	if m != nil {
		return m.SessionUid
	}
	return ""
}

type SessionCreatedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionCreatedResponse) Reset()         { *m = SessionCreatedResponse{} }
func (m *SessionCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*SessionCreatedResponse) ProtoMessage()    {}
func (*SessionCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_12c26b6320f4bed3, []int{1}
}

func (m *SessionCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionCreatedResponse.Unmarshal(m, b)
}
func (m *SessionCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionCreatedResponse.Marshal(b, m, deterministic)
}
func (m *SessionCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionCreatedResponse.Merge(m, src)
}
func (m *SessionCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_SessionCreatedResponse.Size(m)
}
func (m *SessionCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionCreatedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SessionCreatedRequest)(nil), "session.SessionCreatedRequest")
	proto.RegisterType((*SessionCreatedResponse)(nil), "session.SessionCreatedResponse")
}

func init() { proto.RegisterFile("ocpirpc/session.proto", fileDescriptor_12c26b6320f4bed3) }

var fileDescriptor_12c26b6320f4bed3 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcd, 0x4f, 0x2e, 0xc8,
	0x2c, 0x2a, 0x48, 0xd6, 0x2f, 0x4e, 0x2d, 0x2e, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x2c, 0xb8, 0x44, 0x83, 0x21, 0x4c, 0xe7, 0xa2, 0xd4, 0xc4,
	0x92, 0xd4, 0x94, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x79, 0x2e, 0x6e, 0xa8, 0x9a,
	0xf8, 0xd2, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x2e, 0xa8, 0x50, 0x68, 0x66,
	0x8a, 0x92, 0x04, 0x97, 0x18, 0xba, 0xce, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa3, 0x64, 0x2e,
	0x3e, 0xa8, 0x4c, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x50, 0x20, 0x5c, 0x04, 0xaa, 0x56,
	0x48, 0x4e, 0x0f, 0xe6, 0x20, 0xac, 0xd6, 0x4b, 0xc9, 0xe3, 0x94, 0x87, 0x58, 0xe2, 0xa4, 0x19,
	0xa5, 0x9e, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x9c, 0x58, 0x92,
	0x99, 0x9b, 0x5f, 0x92, 0xaf, 0x9f, 0x9e, 0xaf, 0x0b, 0xf2, 0xb1, 0x6e, 0x62, 0x41, 0xa6, 0x3e,
	0xd4, 0xeb, 0x49, 0x6c, 0x60, 0x3f, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x48, 0x21, 0x47,
	0xa0, 0x0c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SessionServiceClient is the client API for SessionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SessionServiceClient interface {
	SessionCreated(ctx context.Context, in *SessionCreatedRequest, opts ...grpc.CallOption) (*SessionCreatedResponse, error)
}

type sessionServiceClient struct {
	cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
	return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) SessionCreated(ctx context.Context, in *SessionCreatedRequest, opts ...grpc.CallOption) (*SessionCreatedResponse, error) {
	out := new(SessionCreatedResponse)
	err := c.cc.Invoke(ctx, "/session.SessionService/SessionCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionServiceServer is the server API for SessionService service.
type SessionServiceServer interface {
	SessionCreated(context.Context, *SessionCreatedRequest) (*SessionCreatedResponse, error)
}

// UnimplementedSessionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSessionServiceServer struct {
}

func (*UnimplementedSessionServiceServer) SessionCreated(ctx context.Context, req *SessionCreatedRequest) (*SessionCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SessionCreated not implemented")
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
	s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_SessionCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServiceServer).SessionCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.SessionService/SessionCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServiceServer).SessionCreated(ctx, req.(*SessionCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SessionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "session.SessionService",
	HandlerType: (*SessionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SessionCreated",
			Handler:    _SessionService_SessionCreated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocpirpc/session.proto",
}
