// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocpirpc/tokenauthorization.proto

package ocpirpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateTokenAuthorizationRequest struct {
	AuthorizationId      string   `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	Authorize            bool     `protobuf:"varint,2,opt,name=authorize,proto3" json:"authorize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTokenAuthorizationRequest) Reset()         { *m = UpdateTokenAuthorizationRequest{} }
func (m *UpdateTokenAuthorizationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTokenAuthorizationRequest) ProtoMessage()    {}
func (*UpdateTokenAuthorizationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b604aee84f6d7c0, []int{0}
}

func (m *UpdateTokenAuthorizationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTokenAuthorizationRequest.Unmarshal(m, b)
}
func (m *UpdateTokenAuthorizationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTokenAuthorizationRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTokenAuthorizationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTokenAuthorizationRequest.Merge(m, src)
}
func (m *UpdateTokenAuthorizationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTokenAuthorizationRequest.Size(m)
}
func (m *UpdateTokenAuthorizationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTokenAuthorizationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTokenAuthorizationRequest proto.InternalMessageInfo

func (m *UpdateTokenAuthorizationRequest) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

func (m *UpdateTokenAuthorizationRequest) GetAuthorize() bool {
	if m != nil {
		return m.Authorize
	}
	return false
}

type UpdateTokenAuthorizationResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTokenAuthorizationResponse) Reset()         { *m = UpdateTokenAuthorizationResponse{} }
func (m *UpdateTokenAuthorizationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTokenAuthorizationResponse) ProtoMessage()    {}
func (*UpdateTokenAuthorizationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b604aee84f6d7c0, []int{1}
}

func (m *UpdateTokenAuthorizationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTokenAuthorizationResponse.Unmarshal(m, b)
}
func (m *UpdateTokenAuthorizationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTokenAuthorizationResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTokenAuthorizationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTokenAuthorizationResponse.Merge(m, src)
}
func (m *UpdateTokenAuthorizationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTokenAuthorizationResponse.Size(m)
}
func (m *UpdateTokenAuthorizationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTokenAuthorizationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTokenAuthorizationResponse proto.InternalMessageInfo

func (m *UpdateTokenAuthorizationResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*UpdateTokenAuthorizationRequest)(nil), "tokenauthorization.UpdateTokenAuthorizationRequest")
	proto.RegisterType((*UpdateTokenAuthorizationResponse)(nil), "tokenauthorization.UpdateTokenAuthorizationResponse")
}

func init() { proto.RegisterFile("ocpirpc/tokenauthorization.proto", fileDescriptor_8b604aee84f6d7c0) }

var fileDescriptor_8b604aee84f6d7c0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x4f, 0x2e, 0xc8,
	0x2c, 0x2a, 0x48, 0xd6, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0x4b, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0xca,
	0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc2, 0x94,
	0x51, 0xca, 0xe2, 0x92, 0x0f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x0d, 0x01, 0xc9, 0x39, 0x22, 0xcb,
	0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x69, 0x72, 0x09, 0xa0, 0xe8, 0x89, 0xcf, 0x4c,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x47, 0x11, 0xf7, 0x4c, 0x11, 0x92, 0xe1, 0xe2,
	0x84, 0x09, 0xa5, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0x21, 0x04, 0x94, 0x8c, 0xb8, 0x14,
	0x70, 0xdb, 0x55, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xc4, 0xc7, 0xc5, 0x94, 0x9f, 0x0d, 0x36,
	0x9e, 0x23, 0x88, 0x29, 0x3f, 0xdb, 0x68, 0x31, 0x23, 0x97, 0x24, 0xa6, 0xf2, 0xe0, 0xd4, 0xa2,
	0xb2, 0xcc, 0xe4, 0x54, 0xa1, 0x56, 0x46, 0x2e, 0x09, 0x5c, 0x46, 0x0a, 0x19, 0xeb, 0x61, 0x09,
	0x09, 0x02, 0x9e, 0x95, 0x32, 0x21, 0x4d, 0x13, 0xc4, 0xd5, 0x4e, 0xaa, 0x51, 0xca, 0xe9, 0x99,
	0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc5, 0x89, 0x25, 0x99, 0xb9, 0xf9, 0x25,
	0xf9, 0xfa, 0xe9, 0xf9, 0xba, 0xa0, 0x48, 0xd1, 0x87, 0xc6, 0x4c, 0x12, 0x1b, 0x38, 0x1e, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xe3, 0x7d, 0xb7, 0xab, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenAuthorizationServiceClient is the client API for TokenAuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenAuthorizationServiceClient interface {
	UpdateTokenAuthorization(ctx context.Context, in *UpdateTokenAuthorizationRequest, opts ...grpc.CallOption) (*UpdateTokenAuthorizationResponse, error)
}

type tokenAuthorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewTokenAuthorizationServiceClient(cc *grpc.ClientConn) TokenAuthorizationServiceClient {
	return &tokenAuthorizationServiceClient{cc}
}

func (c *tokenAuthorizationServiceClient) UpdateTokenAuthorization(ctx context.Context, in *UpdateTokenAuthorizationRequest, opts ...grpc.CallOption) (*UpdateTokenAuthorizationResponse, error) {
	out := new(UpdateTokenAuthorizationResponse)
	err := c.cc.Invoke(ctx, "/tokenauthorization.TokenAuthorizationService/UpdateTokenAuthorization", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenAuthorizationServiceServer is the server API for TokenAuthorizationService service.
type TokenAuthorizationServiceServer interface {
	UpdateTokenAuthorization(context.Context, *UpdateTokenAuthorizationRequest) (*UpdateTokenAuthorizationResponse, error)
}

// UnimplementedTokenAuthorizationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenAuthorizationServiceServer struct {
}

func (*UnimplementedTokenAuthorizationServiceServer) UpdateTokenAuthorization(ctx context.Context, req *UpdateTokenAuthorizationRequest) (*UpdateTokenAuthorizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTokenAuthorization not implemented")
}

func RegisterTokenAuthorizationServiceServer(s *grpc.Server, srv TokenAuthorizationServiceServer) {
	s.RegisterService(&_TokenAuthorizationService_serviceDesc, srv)
}

func _TokenAuthorizationService_UpdateTokenAuthorization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTokenAuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenAuthorizationServiceServer).UpdateTokenAuthorization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenauthorization.TokenAuthorizationService/UpdateTokenAuthorization",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenAuthorizationServiceServer).UpdateTokenAuthorization(ctx, req.(*UpdateTokenAuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenAuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenauthorization.TokenAuthorizationService",
	HandlerType: (*TokenAuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateTokenAuthorization",
			Handler:    _TokenAuthorizationService_UpdateTokenAuthorization_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocpirpc/tokenauthorization.proto",
}
