// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ocpirpc/tokenauthorization.proto

package ocpirpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TokenAuthorizationCreatedRequest struct {
	AuthorizationId      string   `protobuf:"bytes,1,opt,name=authorization_id,json=authorizationId,proto3" json:"authorization_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAuthorizationCreatedRequest) Reset()         { *m = TokenAuthorizationCreatedRequest{} }
func (m *TokenAuthorizationCreatedRequest) String() string { return proto.CompactTextString(m) }
func (*TokenAuthorizationCreatedRequest) ProtoMessage()    {}
func (*TokenAuthorizationCreatedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b604aee84f6d7c0, []int{0}
}

func (m *TokenAuthorizationCreatedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAuthorizationCreatedRequest.Unmarshal(m, b)
}
func (m *TokenAuthorizationCreatedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAuthorizationCreatedRequest.Marshal(b, m, deterministic)
}
func (m *TokenAuthorizationCreatedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAuthorizationCreatedRequest.Merge(m, src)
}
func (m *TokenAuthorizationCreatedRequest) XXX_Size() int {
	return xxx_messageInfo_TokenAuthorizationCreatedRequest.Size(m)
}
func (m *TokenAuthorizationCreatedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAuthorizationCreatedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAuthorizationCreatedRequest proto.InternalMessageInfo

func (m *TokenAuthorizationCreatedRequest) GetAuthorizationId() string {
	if m != nil {
		return m.AuthorizationId
	}
	return ""
}

type TokenAuthorizationCreatedResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenAuthorizationCreatedResponse) Reset()         { *m = TokenAuthorizationCreatedResponse{} }
func (m *TokenAuthorizationCreatedResponse) String() string { return proto.CompactTextString(m) }
func (*TokenAuthorizationCreatedResponse) ProtoMessage()    {}
func (*TokenAuthorizationCreatedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b604aee84f6d7c0, []int{1}
}

func (m *TokenAuthorizationCreatedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenAuthorizationCreatedResponse.Unmarshal(m, b)
}
func (m *TokenAuthorizationCreatedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenAuthorizationCreatedResponse.Marshal(b, m, deterministic)
}
func (m *TokenAuthorizationCreatedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenAuthorizationCreatedResponse.Merge(m, src)
}
func (m *TokenAuthorizationCreatedResponse) XXX_Size() int {
	return xxx_messageInfo_TokenAuthorizationCreatedResponse.Size(m)
}
func (m *TokenAuthorizationCreatedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenAuthorizationCreatedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenAuthorizationCreatedResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TokenAuthorizationCreatedRequest)(nil), "tokenauthorization.TokenAuthorizationCreatedRequest")
	proto.RegisterType((*TokenAuthorizationCreatedResponse)(nil), "tokenauthorization.TokenAuthorizationCreatedResponse")
}

func init() { proto.RegisterFile("ocpirpc/tokenauthorization.proto", fileDescriptor_8b604aee84f6d7c0) }

var fileDescriptor_8b604aee84f6d7c0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x4f, 0x2e, 0xc8,
	0x2c, 0x2a, 0x48, 0xd6, 0x2f, 0xc9, 0xcf, 0x4e, 0xcd, 0x4b, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0xca,
	0xac, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc2, 0x94,
	0x51, 0xf2, 0xe5, 0x52, 0x08, 0x01, 0x89, 0x3a, 0x22, 0x8b, 0x3a, 0x17, 0xa5, 0x26, 0x96, 0xa4,
	0xa6, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x69, 0x72, 0x09, 0xa0, 0x68, 0x8a, 0xcf,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x47, 0x11, 0xf7, 0x4c, 0x51, 0x52, 0xe6,
	0x52, 0xc4, 0x63, 0x5c, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0xd1, 0x32, 0x46, 0x2e, 0x49, 0x4c,
	0x55, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x1d, 0x58, 0x65, 0xa1, 0x66, 0x08, 0x99,
	0xe8, 0x61, 0xf1, 0x1e, 0x21, 0x1f, 0x48, 0x99, 0x92, 0xa8, 0x0b, 0xe2, 0x50, 0x27, 0xd5, 0x28,
	0xe5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2, 0xc4, 0x92, 0xcc,
	0xdc, 0xfc, 0x92, 0x7c, 0xfd, 0xf4, 0x7c, 0x5d, 0x50, 0x58, 0xeb, 0x43, 0x03, 0x3c, 0x89, 0x0d,
	0x1c, 0xbc, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xd2, 0x5e, 0x51, 0x82, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenAuthorizationServiceClient is the client API for TokenAuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenAuthorizationServiceClient interface {
	TokenAuthorizationCreated(ctx context.Context, in *TokenAuthorizationCreatedRequest, opts ...grpc.CallOption) (*TokenAuthorizationCreatedResponse, error)
}

type tokenAuthorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewTokenAuthorizationServiceClient(cc *grpc.ClientConn) TokenAuthorizationServiceClient {
	return &tokenAuthorizationServiceClient{cc}
}

func (c *tokenAuthorizationServiceClient) TokenAuthorizationCreated(ctx context.Context, in *TokenAuthorizationCreatedRequest, opts ...grpc.CallOption) (*TokenAuthorizationCreatedResponse, error) {
	out := new(TokenAuthorizationCreatedResponse)
	err := c.cc.Invoke(ctx, "/tokenauthorization.TokenAuthorizationService/TokenAuthorizationCreated", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenAuthorizationServiceServer is the server API for TokenAuthorizationService service.
type TokenAuthorizationServiceServer interface {
	TokenAuthorizationCreated(context.Context, *TokenAuthorizationCreatedRequest) (*TokenAuthorizationCreatedResponse, error)
}

// UnimplementedTokenAuthorizationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTokenAuthorizationServiceServer struct {
}

func (*UnimplementedTokenAuthorizationServiceServer) TokenAuthorizationCreated(ctx context.Context, req *TokenAuthorizationCreatedRequest) (*TokenAuthorizationCreatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenAuthorizationCreated not implemented")
}

func RegisterTokenAuthorizationServiceServer(s *grpc.Server, srv TokenAuthorizationServiceServer) {
	s.RegisterService(&_TokenAuthorizationService_serviceDesc, srv)
}

func _TokenAuthorizationService_TokenAuthorizationCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenAuthorizationCreatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenAuthorizationServiceServer).TokenAuthorizationCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenauthorization.TokenAuthorizationService/TokenAuthorizationCreated",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenAuthorizationServiceServer).TokenAuthorizationCreated(ctx, req.(*TokenAuthorizationCreatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenAuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenauthorization.TokenAuthorizationService",
	HandlerType: (*TokenAuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenAuthorizationCreated",
			Handler:    _TokenAuthorizationService_TokenAuthorizationCreated_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ocpirpc/tokenauthorization.proto",
}
